### ISSUE TITLE
Real-World experiment details

### ISSUE THREAD

**Issue by lbaermann** [real-stanford/reflect#3]
Thanks for providing this great work and the corresponding dataset!

I am currently looking into the real-world data and have a few questions:

1. Is there a way to map the timestamps (as contained in `replay_buffer.zarr`) to the video frames (as contained in the `video/color` zarr)? For instance, the recording `appleInFridge1` has length 12816 for all of the modalities in `replay_buffer.zarr` but only 8942 frames in the color/depth videos. How does this align?
2. What is the meaning of the following keys in the `replay_buffer.zarr`: `meta/episode_ends` and `data/stage`?
3. Can you provide additional details on how you created the hierarchical summary for the real-world  data, or perhaps even share the code? You mention in the paper which models you used for object (state) and sound detection, but how did you obtain details about the current task/action/goal? E.g. the event-based summary contains "robot action" field, or the progressive failure explanation needs access to "task name", "goal state" and "original robot plan".

Thank you very much in advance!

**Comment by lzylucy** [comment]
Hi Leonard,

Thanks for your interest in our work and codebase! Here are the answers to your questions:
1.  For this example, please only use the first 8942 frames for all modalities. There was a mistake when saving the data for this example, I'll fix it in the dataset soon.
2. `meta/stage` is an array where the length is the total frames of the episode. The values indicate the corresponding subgoal for each frame. For example, if the `meta/stage` array contains 50 0s and then 50 1s, it means the 50 frames correspond to subgoal 0, and the following 50 frames correspond to subgoal 1. Subgoals are primitive actions as described in the paper such as pick up apple, open fridge.
`meta/episode_ends` indicates the end index for each episode. For all the real world tasks, there should be only 1 episode, in other words, the length of the `'meta/episode_ends` array is 1. For the appleInFridge1 example, `meta/episode_ends` is array([ 8944, 12816]),  there's an extra episode from frame 8944 to frame 12816 that's not relevant and accidentally included.
3. In both simulation and real world, we assume we know the task, goal, and subgoals, in other words, we assume we have access to the 'original robot plan' and task configurations (e.g. task name, goal state) when generating the summary.

Hope this helps and please let me know if you have any other questions!

Zeyi

**Comment by lbaermann** [comment]
Hi Zeyi,

thanks for these helpful answers! 

I understand that the task and plan are assumed to be given. For the simulated data, this can be found in the `task.json` files of each episode. Do you have similar files for the real-world data? This would especially be useful to get the semantics of the `meta/stage` entries (without manually reviewing the videos).

Thanks in advance!
Leonard

**Comment by lzylucy** [comment]
Hi Leonard,

Thanks for the catch! I just uploaded`tasks_real_world.json` which contains configuration for the 30 real world tasks.
https://github.com/real-stanford/reflect/blob/main/main/tasks_real_world.json

Zeyi
